// src/pages/BasePage.js
import React, { useState } from "react";
import styles from './BasePage.module.css';
import imagen from '../assets/Neuronize.jpg';
import Chat from '../components/Chat';

function BasePage() {
  // Estado para guardar la última gráfica generada
  const [lastChartJson, setLastChartJson] = useState(null);

  // Callback para recibir la gráfica desde Chat
  const handleChartGenerated = (chartJson) => {
    setLastChartJson(chartJson);
  };

  return (
    <div className={`${styles.wrapper} ${styles.backgroundEffect}`}>
      <div className={styles.container}>
        <div className={styles.glowAccent} />
        <div className={styles.glowAccent} />

        <header className={styles.header}>
          <h1>🤖 Neuronize - Industrial Intelligence Platform</h1>
          <p>Neuronize is our industrial intelligence proposal to interconnect and enhance the value generated by company processes. We apply advanced digital architectures that leverage every asset in the plant through a universal connectivity strategy.</p>
        </header>

        <main className={styles.mainContent}>
          <div className={styles.infoSection}>
            <h2>About Neuronize Platform</h2>
            <p>Neuronize is our industrial intelligence proposal to interconnect and enhance the value generated by company processes. We apply advanced digital architectures that leverage every asset in the plant through a universal connectivity strategy.</p>
            
            <p>Our platform transforms traditional manufacturing operations by creating intelligent connections between all industrial assets, enabling real-time data analysis and predictive insights to optimize production workflows.</p>

            <h3>Platform Capabilities:</h3>
            <ul className={styles.features}>
              <li>Enhance connected and digitized assets</li>
              <li>Provides intelligence to assets</li>
              <li>Allows you to create a neural network with assets</li>
              <li>Produce better, higher efficiency, lower cost</li>
              <li>Universal connectivity strategy implementation</li>
              <li>Advanced digital architecture deployment</li>
            </ul>
          </div>
          <div className={styles.imageSection}>
            <img
              src={imagen}
              alt="Sistema Industrial de Manufactura Inteligente"
              className={styles.illustration}
            />
          </div>
        </main>

        <div className={styles.chatbotContainer} id="chatbot-container">
          <div className={styles.chatbotInfo}>
            <h3>💬 Neuronize AI Assistant</h3>
            <p>
              Your intelligent assistant for industrial data analysis is ready
            </p>
          </div>
          <div style={{ marginTop: 2, width: '100%' }}>
            {/* Pasar el callback a Chat */}
            <Chat onChartGenerated={handleChartGenerated} />
          </div>
        </div>
      </div>
    </div>
  );
}

export default BasePage;
