import React from "react";
import "./Neuronize.css";
import illustration from "./assets/Image (10).jpg"; // Asegúrate de tener la imagen

export default function NeuronizePage() {
  return (
    <div className="container">
      <div className="glow-accent" />
      <div className="glow-accent" />

      <header className="header">
        <h1>🤖 Neuronize - Industrial Intelligence Platform</h1>
        <p>
          Neuronize is our industrial intelligence proposal to interconnect and
          enhance the value generated by company processes...
        </p>
      </header>

      <main className="main-content">
        <div className="info-section">
          <h2>About Neuronize Platform</h2>
          <p>Neuronize is our industrial intelligence...</p>
          <h3>Platform Capabilities:</h3>
          <ul className="features">
            <li>Enhance connected and digitized assets</li>
            <li>Provides intelligence to assets</li>
            <li>Allows you to create a neural network with assets</li>
            <li>Produce better, higher efficiency, lower cost</li>
            <li>Universal connectivity strategy implementation</li>
            <li>Advanced digital architecture deployment</li>
          </ul>
        </div>
        <div className="image-section">
          <img
            src={illustration}
            alt="Sistema Industrial de Manufactura Inteligente"
            className="manufacturing-illustration"
          />
        </div>
      </main>

      <div className="chatbot-container" id="chatbot-container">
        <div className="chatbot-info">
          <h3>💬 Neuronize AI Assistant</h3>
          <p>
            Your intelligent assistant for industrial data analysis is ready...
          </p>
          <div className="connection-status">
            <p>
              <strong>🔗 Connected with Neuronize Platform</strong>
              <br />
              The chatbot can help you with queries...
            </p>
          </div>
          <div className="loading-animation">
            <div className="dot" />
            <div className="dot" />
            <div className="dot" />
          </div>
        </div>
      </div>
    </div>
  );
}
